export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_PRODUCT_IN_CART = 'DELETE_PRODUCT_IN_CART';
export const UPDATE_PRODUCT_IN_CART = 'UPDATE_PRODUCT_IN_CART';
export const CHANGE_MESSAGE = 'CHANGE_MESSAGE';

export const GET_POSTS = 'GET_POSTS';

export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const DELETE_PRODUCT_IN_WISHLIST = 'DELETE_PRODUCT_IN_WISHLIST';


// export const ADD_TO_ACCOUNT = 'ADD_TO_ACCOUNT';
// export const DELETE_PRODUCT_IN_ACCOUNT = 'DELETE_PRODUCT_IN_ACCOUNT';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';



